### ISSUE TITLE
Partner with another AEK II project for a commercially available version?

### ISSUE THREAD

**Issue by quorten** [kb-elmo/aek2_usb#1]
Hello there,

Whoah, I just found your project today but maybe us folks on this other project should have seen it earlier.  Mark from MacEffects (https://maceffects.com/) was interested in designing a AEK II clone with both USB and ADB support, all the mechanical design has already been done, what is left is just the PCB, like, almost your project verbatim.

Me, I'm just an interested community member, but yeah I wanted to reach out by some communication means to start the discussion.  Would you be interested in participating in the MacEffects project?

I noticed your project is licensed for non-commercial use only, so yeah, it's really up to you if you want to permit a license for this particular commercial use.  Mark said that he would be willing to add your expenses to the project total too.

Also, we can find more ways to get you in contact with the community and Mark if you're interested, right now most of the community discussion is happening on the 68kMLA.org forum.

**Comment by kb-elmo** [comment]
Hi there,

this sounds like a really nice plan but I don't think that my PCB would be the right choice for this as it is only meant to be compatible with USB and specifically the QMK firmware.
To get it to work with ADB it would require a complete redesign since it is missing all the electronic components that are required for that and I'm not even sure if the QMK firmware would even support ADB (meaning a new firmware would probably be required as well).

Since I never worked with any ADB related stuff I don't think that I would be able to do such a redesign in a reliable good enough way for this project (I'm everything but a professional PCB designer).

**Comment by quorten** [comment]
Thanks for your response.  Probably the path Mark's AEK clone project would go down anyways would involve working with his existing professional PCB design contact once he/she finished other PCB design projects he/she is currently busy with.

So, that being said, I'm personally going to end up tinkering around with these designs and hope at least some inspiration from the good ideas in your previous efforts can end up in the commercial product.

Also, my personal, humble opinion about the license for this project.  I recently saw that the Bakeneko 60 open hardware keyboard had to get pulled from GitHub and the group buy idea canceled due to a miscommunication about the licensing of the case design for open-source and commercial reuse, I feel that was a real bummer that had to happen.

So... in light of that, I feel it is worthwhile to put in a little bit of extra effort in clear communications about licensing matters.  Maybe an update to the README indicating you wholeheartedly support independent parties doing a PCB design from scratch to clarify what you mean by "non-commercial use" for this project, and maybe even changing the license of this project to remove the non-commercial use clause, that could be appreciated.

**Comment by kb-elmo** [comment]
I'm not exactly sure what you point about the license is?

I certainly don't own any rights for retrofit AEK II PCBs in general.
If someone decides to make his own retrofit PCB for the board then it doesn't fall under the license of this project at all.

**Comment by quorten** [comment]
Yeah really, that's really all there is to my point about the license.  Nothing too special other than possibly adding a note to the README stating you don't own any rights to retrofit AEK II PCBs.
