### ISSUE TITLE
tenkeyless option?

### ISSUE THREAD

**Issue by kan2k** [kb-elmo/aek2_usb#2]
as title, would be nice

**Comment by kb-elmo** [comment]
for what?

You do understand that this is a replacement PCB for the Apple AEK II? A keyboard made in the 80s?  
This isn't a complete keyboard and there was no tenkeyless version of the AEK II available.

So there wouldn't be any point in making a TKL version of this.

**Comment by kan2k** [comment]
Yeah, I do know that. I am asking because I wanted to mod my AEK2 to a TKL version. Sorry for not being specific on what I am doing.

**Comment by kb-elmo** [comment]
you are free to fork and mod this if you want

**Comment by kan2k** [comment]
will do thanks
