### ISSUE TITLE
Dumb question

### ISSUE THREAD

**Issue by djvs** [kb-elmo/aek2_usb#3]
Any thoughts on ease of supporting more easily/broadly supported Atmega32u4?  Or stm32f?   I think it's just basically changing the controller footprint?  I was staring at your rep in Kicad but I have next to no idea what I'm doing.

**Comment by kb-elmo** [comment]
> I think it's just basically changing the controller footprint?

That's definitely not how that works.

Changing the controller would not only require redesigning pretty much all the electroncis on the board but also to rewrite the firmware for the PCB since you can't just use entirely different controllers interchangeably.

I have no plans for doing that.

**Comment by djvs** [comment]
There are some alternate PCBs being worked on for this, I just figured if changing the kicad parts was a 5 minute change for you it might simpler.

**Comment by kb-elmo** [comment]
> Well, the firmware "rewrite" is a given (though this should be pretty much automatic with QMK, which is the point of using a more common controller)

It absolutely isn't.
Especially not with an STM32 controller.


> but isn't the electronics change basically just changing the termination points of the matrix?

Again. No it isn't.
Atmega32a, Atmega32u4 and _especially_ the STM32 series are completely different controllers that are not compatible with each other in _any_ way.
They require vastly different electronics for the biggest part of the PCB and changing all of that would take quite a bit more than "just 5 minutes".

Maybe inform yourself a bit more about how the electronics of these controllers work.
